// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package exercises

// Injectors from wire.go:

// InitializeExerciseApp 声明带两个清理函数的练习依赖图。
func InitializeExerciseApp(log *CleanupLog) (*ExerciseApp, func()) {
	resourceA, cleanup := NewResourceA(log)
	resourceB, cleanup2 := NewResourceB(resourceA, log)
	exerciseApp := NewExerciseApp(resourceB)
	return exerciseApp, func() {
		cleanup2()
		cleanup()
	}
}
