// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireexample

// Injectors from wire.go:

// InitializeApp 声明 App 的 Wire 依赖图。
func InitializeApp(config Config) (*App, func(), error) {
	wireexampleMemoryRepository, cleanup, err := NewMemoryRepository(config)
	if err != nil {
		return nil, nil, err
	}
	service := NewService(wireexampleMemoryRepository, config)
	app := NewApp(service)
	return app, func() {
		cleanup()
	}, nil
}
